/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed n, 
find the sum of the even-valued terms. */

function fiboEvenNum(num){
    let sum;
    if (num>0){
        let fiboArr=[1,1];
        let fiboNum=1;
        if(num<3){
            sum=0;
        }else{
            for(let i=2; fiboArr[i-1]<num ; i++){
                fiboNum=fiboArr[i-1]+fiboArr[i-2];
                if(fiboNum<=num){
                    fiboArr.push(fiboNum);
                };
            };
            console.log(fiboArr);
            sum=fiboArr.reduce((sum,item)=>{
                if(item%2==0){
                    sum=sum+item;
                };
                return sum;
            },0)
        };
    } else {
        console.log("Introducir un número mayor a cero");
    };
    return sum;
};

console.log(fiboEvenNum(15));
console.log(fiboEvenNum(8));
console.log(fiboEvenNum(0));

function par(arr){
    arr.map(item=>{
        if(item%2==0){
            console.log("par",item)
        }
    },0)
}
par([2,3,5,8,13])